### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Where is that library? Maybe this should be fixed there too.

**Comment by dark-panda** [comment]
It's part of GEOS itself. I think it throws a LoadError as a consequence of how Ruby loads dynamic libraries and not so much the library itself. It's just how Ruby operates, but ffi works a little differently, so this was a matter of trying to make the two operate similarly. It's been a while since I wrote that code, but I think that was the rationale.

**Comment by deivid-rodriguez** [comment]
Ok, I understand what you're saying now, you try to behave just like [GEOS' Ruby bindings](https://github.com/libgeos/libgeos/tree/svn-trunk/swig/ruby).

However, I'm not sure compatibility means anything here. In libgeos you have to compile the library with Ruby bindings enabled, whereas here you have to load this FFI thing.

I think we should help users troubleshoot problems and specific and accurate errors help. I had to remove the rescue lines to find out the actual error I was getting...

**Comment by dark-panda** [comment]
What was the error in that case? Do you recall?

**Comment by deivid-rodriguez** [comment]
It's in the commit message.

**Comment by dark-panda** [comment]
One of the original design goals was to be a drop in replacement for the native library, so any deviation from that would have been contrary to that goal. However, over the years I've forged ahead adding features to ffi-geos while the native bindings have basically been abandoned, so it might be time to revisit the design goal and decide if it's still worth it to keep the more pedantic bits in.

**Comment by dark-panda** [comment]
Checking for the existence of of a constant to determine whether or not a library has been loaded doesn't seem more helpful to me than an exception flat out telling you the library hasn't been loaded though? I do that in this case so I have a consistent error to raise and for the aforementioned compatibility, but are you saying you also do the same user-side to check for the library's existence?

**Comment by deivid-rodriguez** [comment]
No no, I was just trying to have a look at the code and get the tests passing. :)

I got this error, went to the source code and saw a block that would rescue some exceptions and then reraised them. But I still didn't know where and why the error happened. After removing the rescues I saw that FFI loaded stuff ok, but the methods were just not available.

In any case, it's no big deal!

**Comment by dark-panda** [comment]
What version of GEOS are you using? Not all methods are available on all versions of the GEOS library, so that could be it.

**Comment by deivid-rodriguez** [comment]
I actually fixed the issue after I realized I was missing the library. My point is that I had to dig in a bit deeper and remove the rescue clause to find out.

**Comment by dark-panda** [comment]
Ah, gotcha. Let me think about it a bit. Perhaps I should make the error clearer and provide some error resolution advice when the exception is raised.

**Comment by deivid-rodriguez** [comment]
:+1: Improving the error message, at least adding the original exception message would be good too!

**Comment by dark-panda** [comment]
As of Ruby 2.1+, you can look at the `Exception#cause` method and you'll find the original exception, which in this case, at least on my system for similar errors, looks like this:

```
#<LoadError: Could not open library '/usr/local/lib/libgeos_c.dylib': dlopen(/usr/local/lib/libgeos_c.dylib, 5): image not found>
```

**Pull request closed without merging**
